### ISSUE TITLE
Deprecate support for node@0.10?

### ISSUE THREAD

**Issue by theworkflow** [onmodulus/knock-knock#16]
In the package.json we note that we support node@0.10. Running the tests for the repo under that node version yields [errors](https://travis-ci.org/onmodulus/knock-knock/builds/146210992).

**Comment by theworkflow** [comment]
I say we deprecate it since it will not longer be supported soon. Plus since it currently fails tests, we can either make the code pass, or just remove it as a supported version.

**Comment by fiveisprime** [comment]
Yeah, 0.10 falls out of maintenance in October so I don't see any reason to support it. Related, node 0.12 is out of active LTS as of April and falls out of maintenance in December so I wouldn't bother with that either.

I say just jump straight to 6. 👌

**Comment by franvarney** [comment]
Do we want to refactor to use es6 features, too?

**Comment by fiveisprime** [comment]
I say yeah

**Comment by jackboberg** [comment]
`4.x LTS` will be supported thru April 2018, maybe we continue supporting that for a bit before purposefully rewriting working code to drop support...

Totally on board with dropping support for `< 4.x`. 👍
